export const PREDEFINED_PATTERNS = [
  "Two Pointers",
  "Sliding Window",
  "Fast and Slow Pointers",
  "Prefix Sum",
  "Binary Search",
  "Cyclic Sort",
  "Merge Intervals",
  "In-place Linked List Reversal",
  "Breadth-First Search",
  "Depth-First Search",
  "Topological Sort",
  "Union Find",
  "Monotonic Stack",
  "Top K Elements",
  "K-way Merge",
  "Backtracking",
  "Dynamic Programming",
  "Greedy",
  "Kadane's Algorithm",
  "Divide and Conquer",
  "Bit Manipulation",
] as const;
