export const PREDEFINED_TOPICS = [
  "Array",
  "String",
  "Hashing",
  "Linked List",
  "Stack",
  "Queue",
  "Tree",
  "Binary Tree",
  "Binary Search Tree",
  "Heap",
  "Graph",
  "Trie",
  "Recursion",
  "Backtracking",
  "Dynamic Programming",
  "Greedy",
  "Bit Manipulation",
  "Math",
  "Sorting",
  "Searching",
  "Matrix",
] as const;
